# Generated by Django 5.0.4 on 2024-04-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eFormApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='title',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
