# Generated by Django 5.0.4 on 2024-04-04 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eFormApp', '0002_produit_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='title',
            new_name='content',
        ),
    ]
